server:
  port: 8083

spring:
  application:
    name: department-service
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /sv-dep/swagger-ui.html
  api-docs:
    path: /sv-dep/v2/api-docs
  show-actuator: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
